In [2]:
import numpy as np

marks=[10,20,30,40,50]

print(marks*2)

new_marks=np.array(marks)
print(new_marks*2)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 20  40  60  80 100]


In [4]:
zeros= np.zeros(5)
print(zeros)


[0. 0. 0. 0. 0.]


In [5]:
ones = np.ones((3, 4))

ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
data=[1,4,9,16,25,-1]
data = np.array(data)

np.sqrt(data)

/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_52172/1519383530.py:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data)


array([ 1.,  2.,  3.,  4.,  5., nan])

In [8]:
ones = np.ones((3, 4))

ones.reshape(4, 3)


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import pandas as pd

marks=[10,20,30,40,50]

#create series from marks
new_marks=pd.Series(marks)

new_marks